### ISSUE TITLE
Can this lib sign the certs?

### ISSUE THREAD

**Issue by sledro** [NotSimple/blockcert-tools-js#2]
Hey, thanks for the awesome lib. Can it be used to sign and verify certs in nodejs?

**Comment by notsimple** [comment]
Hi! Sorry for not responding earlier, for some reason I didn't notice you created an issue. This node package is only for generating blockcert certificate templates and instantiating certificate batches. The ability to sign and verify certs is not the focus of this lib. 

To verify certs with node js you can use [cert-verifier-js](https://www.npmjs.com/package/@blockcerts/cert-verifier-js). As for signing certificates: I haven't been active in the blockcerts space lately, but last time I checked there wasn't a open source implementation for Node JS. I personally used the python [cert-issuer](https://github.com/blockchain-certificates/cert-issuer) which worked fine.
